### ISSUE TITLE
Organisation aufsetzen

### ISSUE THREAD

**Issue by 7ben18** [AdversarialAttacks/.github#1]
Administrative Aufgaben die wir vor dem Kickoff Gespräch erledigen wollen. 

**Quellcode**
- [x] Organisation erstellen
- [x] ~Repository Struktur definieren -> [cookiecutter](https://github.com/cookiecutter/cookiecutter)~

**Dokumentation**
- [x] Zotero einrichten
- [x] Protokolltemplate aufsetzen

**Projektmangement**
- [x] Taskboard aufsetzen
- [ ] Betreuer haben Zugriff auf GitHub Organisation

**Comment by 7ben18** [comment]
## Overleaf Synchronisation mit GitHub

Änderungen auf Overleaf können auf GitHub committet werden. Dabei wie folgt vorgehen:

1.  Projekt Menü öffnen
![Image](https://github.com/AdversarialAttacks/.github/assets/66916399/d504219f-a573-4376-b1ec-14a837d70e69)

2. Unter **Sync** GitHub auswählen & anschliessend auf das Repository pushen


![Image](https://github.com/AdversarialAttacks/.github/assets/66916399/699ee0aa-9614-4ebf-8848-ed2acb6fd184)

**Comment by 7ben18** [comment]
# Integration Zotero in Overleaf

Damit wir zitieren können benötigen wir von Zotero die "bib" Datei. Overleaf bietet uns eine einfache Integration mit Zotero an. 

1. Zotero Integration setup
Unter Account -> Account Setting -> [Reference Managers](https://www.overleaf.com/user/settings) -> Zotero Integration -> Link anklicken.


![Image](https://github.com/AdversarialAttacks/.github/assets/66916399/8121565d-7c0c-469b-b08e-9212b1167cda)

2. Upload bib Datei von Zotero


![Image](https://github.com/AdversarialAttacks/.github/assets/66916399/de41ffcf-89a2-4a66-8567-ebff7c17b130)



![Image](https://github.com/AdversarialAttacks/.github/assets/66916399/39972b7e-fbbf-4764-80e9-8d7e3b84290c)

**Comment by gabrieltorresgamez** [comment]
Should we close this ticket?

**Comment by 7ben18** [comment]
> Should we close this ticket?

Nope, Username von Betreuer nicht vorhanden. 
Ansprechen in der Sitzung vom 27.02.2024. 

Mein Vorschlag: 
Falls bis Ende Februar (29.02.2024) Username der Betreuer nicht bekannt ist, wird das Ticket automatisch geschlossen.
