### ISSUE TITLE
Report aufsetzen

### ISSUE THREAD

**Issue by gabrieltorresgamez** [AdversarialAttacks/.github#4]
- [x] OverLeaf einrichten und verbinden mit Repository
- [x] Zotero und Overleaf
- [x] GitHub und Overleaf

**Comment by 7ben18** [comment]
### Tex Template Done
Overleaf Template aufgesetzt. 

### Bemerkung
Ab und zu lohnt es sich den Cache zu leeren bevor man recompiled. 


![Image](https://github.com/AdversarialAttacks/.github/assets/66916399/cf171c11-1e22-4d0b-96d2-8f31dac6e9d5)
